FROM ubuntu:latest

RUN apt-get update && apt-get install -y systemd gnupg2 && \
    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 68818C72E52529D4 && \
    echo "deb http://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-4.0.list && \
    apt-get update && \
    apt-get install -y mongodb-org && \
    sed -i 's/bindIp/# bindIp/g' /etc/mongod.conf && \
    mkdir -p /home/core && \
    cd /home/core && \
    openssl rand -base64 741 > mongodb-keyfile && \
    chmod 600 mongodb-keyfile && \
    chown 999 mongodb-keyfile

# Define mountable directories.
VOLUME ["/data/db"]

# Define working directory.
WORKDIR /data

# Define default command.
CMD ["mongod", "--bind_ip_all"]

# Expose ports.
#   - 27017: process
#   - 28017: http
EXPOSE 27017
EXPOSE 28017
